### ISSUE TITLE
Spelling Corrrection - Spectrum

### ISSUE THREAD

**Issue by samsherwood** [KevinJump/umbracoPeriodic#1]
https://github.com/KevinJump/umbracoPeriodic/blob/46b26432cc44e0dba302116046b17f4324604fae/index.html#L89

Spectrum is misspelled 'Specturm' in title of module.

Should be...
`<div class="title">Spectrum Colour Picker</div>`

**Comment by KevinJump** [comment]
Indeed - fixed now.

**Comment by samsherwood** [comment]
fwiw, our team really dug reading through this today :)
